version: '3'

networks:
  internal:
    external: false
  web:
    external: true

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:latest
#    command: --docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.port=${DASHBOARD_PORT}"

  db:
    container_name: klubitus-db
    image: postgres:11-alpine
#    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_INITDB_ARGS=-E UTF8 --locale=fi_FI.UTF8
    networks:
      - internal
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    restart: always
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./db/logs:/logs
      - ./db/logs:/var/log/postgresql
      - db-data:/var/lib/postgresql/data
#      - ./dump.sql:/tmp/dump.sql
    labels:
      - "traefik.enable=false"

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: klubitus-api
    restart: always
    command: yarn start:dev
    volumes:
      - ./api/src:/srv/api/src
      - ./api/package.json:/srv/api/package.json
      - ./api/tsconfig.json:/srv/api/tsconfig.json
      - ./api/tsconfig.build.json:/srv/api/tsconfig.build.json
      - ./api/upload:/srv/api/upload
#      - /srv/api/node_modules
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET
      - AWS_DEFAULT_REGION
      - AWS_IMAGE_PREFIX
      - API_PORT
      - DB_HOST=db
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
      - FB_APP_ID
      - FB_CLIENT_TOKEN
      - NODE_ENV=development
    networks:
      - internal
      - web
    expose:
      - ${API_PORT}
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_HOST}`)"
#      - "traefik.http.routers.default.tls.certresolver=default"
      - "traefik.port=${API_PORT}"
    depends_on:
      - reverse-proxy

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: klubitus-client
    restart: always
    command: yarn dev
    volumes:
      - ./client/src:/srv/client/src
      - ./client/nuxt.config.ts:/srv/client/nuxt.config.ts
      - ./client/tsconfig.json:/srv/client/tsconfig.json
      - ./client/package.json:/srv/client/package.json
    environment:
      - API_HOST
      - API_PORT
      - API_PROTOCOL
      - "API_URL_BROWSER=${API_PROTOCOL}://${API_HOST}"
      - AWS_BUCKET
      - CLIENT_HOST
      - CLIENT_PORT
      - FB_APP_ID
      - FB_CLIENT_TOKEN
      - NODE_ENV=development
    networks:
      - web
    links:
      - "api:${API_HOST}"
    expose:
      - ${CLIENT_PORT}
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.port=${CLIENT_PORT}"
    depends_on:
      - reverse-proxy

volumes:
  db-data:
